# Ensure 24-bit color is enabled and TERM is widely supported
export COLORTERM=truecolor
if [[ "$TERM" == "wezterm" ]]; then
  export TERM=xterm-256color
fi

# Prompt
eval "$(starship init zsh)"

if [[ -f "$HOME/.asdf/asdf.sh" ]]; then
  . "$HOME/.asdf/asdf.sh"
fi

if [[ -f "$HOME/.opam/opam-init/init.zsh" ]]; then
  eval $(opam env)
fi

# asdf
ASDF_BIN=$(dirname $(readlink $(which asdf)))
ASDF_SOURCE_PATH=$(realpath "$ASDF_BIN/../share/asdf-vm/asdf.sh")
source "$ASDF_SOURCE_PATH"

alias dc="docker compose"
alias tf='terraform'

# RipGrep
alias rg="rg --hidden"

# Git

alias gst='git status'
alias ggp='git push origin HEAD:refs/for/master'
alias gm='git commit -m '
alias gca='git commit --amend'
alias gco='git checkout'
alias gbl='git branch --sort=-committerdate'

alias mystow='stow -d $HOME/nixos/ -t $HOME/.config .config'

function backup(){
  cp $1 $1.bak
}

# Outputs the name of the current branch
# Usage example: git pull origin $(git_current_branch)
# Using '--quiet' with 'symbolic-ref' will not cause a fatal error (128) if
# it's not a symbolic ref, but in a Git repo.
function current_branch() {
  local ref
  ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return  # no git repo.
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
  fi
  echo ${ref#refs/heads/}
}

# Default git push to current branch
function gpoc {
  echo Pushing $(current_branch)
  git push origin $(current_branch)
}

function gfpoc {
  echo FORCE Pushing $(current_branch)
  git push -f  --set-upstream origin $(current_branch)
}

# Default git pull from current branch
function gploc {
  echo Pulling $(current_branch)
  git pull origin $(current_branch)
}

alias gbsm='git branch --merged | egrep -v "(^\*|master|dev)"'
alias gbdm='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'

if [ -f "$HOME/.cargo/env" ]; then
  # shellcheck disable=SC1090
  # shellcheck source=/dev/null
  . "$HOME/.cargo/env"
fi
