# Prompt
eval "$(starship init zsh)"


# RipGrep
alias rg="rg --hidden"

# Git

alias gst='git status'
alias ggp='git push origin HEAD:refs/for/master'
alias gm='git commit -m '
alias gca='git commit --amend'
alias gco='git checkout'
alias gbl='git branch --sort=-committerdate'

# Outputs the name of the current branch
# Usage example: git pull origin $(git_current_branch)
# Using '--quiet' with 'symbolic-ref' will not cause a fatal error (128) if
# it's not a symbolic ref, but in a Git repo.
function current_branch() {
  local ref
  ref=$(command git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?
  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return  # no git repo.
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return
  fi
  echo ${ref#refs/heads/}
}

# Default git push to current branch
function gpoc {
  echo Pushing $(current_branch)
  git push origin $(current_branch)
}

function gfpoc {
  echo FORCE Pushing $(current_branch)
  git push -f  --set-upstream origin $(current_branch)
}

# Default git pull from current branch
function gploc {
  echo Pulling $(current_branch)
  git pull origin $(current_branch)
}

alias gbsm='git branch --merged | egrep -v "(^\*|master|dev)"'
alias gbdm='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d'
